import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sagnik @ 2021-08-18T11:00:00.000Z',
  description: 'Generated by Sagnik @ 2021-08-18T11:00:00.000Z',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
